default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  host: localhost

development:
  <<: *default
  database: amazon_development
  username: amazon
  password: password

test:
  <<: *default
  database: amazon_test
  username: amazon
  password: password

#production:
# <<: *default
 # database: amazon_production
 # username: amazon
 # password: password